server:
  port: 8081
  servlet:
    path: /springboot
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/zqs
      username: root
      password: root
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/
  thymeleaf:
    cache: false
    enabled: false
  jpa:
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
  redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 3000ms
  data:
   mongodb:
     database: lly
     host: localhost
     port: 27017


mybatis:
  type-aliases-package: com.jk.pojo



